<?php

namespace PackageVersions;

/**
 * This class is generated by ocramius/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
    const ROOT_PACKAGE_NAME = '__root__';
    const VERSIONS = array (
  'behat/transliterator' => 'v1.2.0@826ce7e9c2a6664c0d1f381cbb38b1fb80a7ee2c',
  'cboden/ratchet' => 'v0.4.1@0d31f3a8ad4795fd48397712709e55cd07f51360',
  'curl/curl' => '2.2.0@d22086dd2eee5ca02e4c29b9a5bdf3645bfdbbff',
  'doctrine/annotations' => 'v1.6.0@c7f2050c68a9ab0bdb0f98567ec08d80ea7d24d5',
  'doctrine/cache' => 'v1.8.0@d768d58baee9a4862ca783840eca1b9add7a7f57',
  'doctrine/collections' => 'v1.5.0@a01ee38fcd999f34d9bfbcee59dbda5105449cbf',
  'doctrine/common' => 'v2.9.0@a210246d286c77d2b89040f8691ba7b3a713d2c1',
  'doctrine/dbal' => 'v2.8.0@5140a64c08b4b607b9bedaae0cedd26f04a0e621',
  'doctrine/doctrine-bundle' => '1.9.1@703fad32e4c8cbe609caf45a71a1d4266c830f0f',
  'doctrine/doctrine-cache-bundle' => '1.3.3@4c8e363f96427924e7e519c5b5119b4f54512697',
  'doctrine/doctrine-migrations-bundle' => 'v1.3.1@a9e506369f931351a2a6dd2aef588a822802b1b7',
  'doctrine/event-manager' => 'v1.0.0@a520bc093a0170feeb6b14e9d83f3a14452e64b3',
  'doctrine/inflector' => 'v1.3.0@5527a48b7313d15261292c149e55e26eae771b0a',
  'doctrine/instantiator' => '1.1.0@185b8868aa9bf7159f5f953ed5afb2d7fcdc3bda',
  'doctrine/lexer' => 'v1.0.1@83893c552fd2045dd78aef794c31e694c37c0b8c',
  'doctrine/migrations' => 'v1.8.1@215438c0eef3e5f9b7da7d09c6b90756071b43e6',
  'doctrine/orm' => 'v2.6.2@d2b4dd71d2a276edd65d0c170375b445f8a4a4a8',
  'doctrine/persistence' => 'v1.0.1@af1ec238659a83e320f03e0e454e200f689b4b97',
  'doctrine/reflection' => 'v1.0.0@02538d3f95e88eb397a5f86274deb2c6175c2ab6',
  'egulias/email-validator' => '2.1.6@0578b32b30b22de3e8664f797cf846fc9246f786',
  'evenement/evenement' => 'v3.0.1@531bfb9d15f8aa57454f5f0285b18bec903b8fb7',
  'friendsofsymfony/rest-bundle' => '2.4.0@3725279a6554c1d894eee0b377f49d3f69e3c217',
  'gedmo/doctrine-extensions' => 'v2.4.36@87c78ff9fd4b90460386f753d95622f6fbbfcb27',
  'guzzlehttp/psr7' => '1.4.2@f5b8a8512e2b58b0071a7280e39f14f72e05d87c',
  'jdorn/sql-formatter' => 'v1.2.17@64990d96e0959dff8e059dfcdc1af130728d92bc',
  'jms/metadata' => '1.6.0@6a06970a10e0a532fb52d3959547123b84a3b3ab',
  'jms/parser-lib' => '1.0.0@c509473bc1b4866415627af0e1c6cc8ac97fa51d',
  'jms/serializer' => '1.13.0@00863e1d55b411cc33ad3e1de09a4c8d3aae793c',
  'jms/serializer-bundle' => '2.4.2@22eb9a2f7983394b0770237ca91e879eb2a4b4a6',
  'knplabs/knp-snappy' => 'v1.1.0@ea037298d3c613454da77ecb9588cf0397d695e1',
  'knplabs/knp-snappy-bundle' => 'v1.6.0@87acf8544a2bd498585b3d49b2bb551f088551b1',
  'lcobucci/jwt' => '3.2.4@c9704b751315d21735dc98d78d4f37bd73596da7',
  'lexik/jwt-authentication-bundle' => 'v2.5.4@f1c8c9a33c55eeb6105de5a2aedb9ba44a6efbed',
  'monolog/monolog' => '1.23.0@fd8c787753b3a2ad11bc60c063cff1358a32a3b4',
  'namshi/jose' => '7.2.3@89a24d7eb3040e285dd5925fcad992378b82bcff',
  'nikic/php-parser' => 'v4.1.0@d0230c5c77a7e3cfa69446febf340978540958c0',
  'ocramius/package-versions' => '1.3.0@4489d5002c49d55576fa0ba786f42dbb009be46f',
  'ocramius/proxy-manager' => '2.2.2@14b137b06b0f911944132df9d51e445a35920ab1',
  'phpcollection/phpcollection' => '0.5.0@f2bcff45c0da7c27991bbc1f90f47c4b7fb434a6',
  'phpoption/phpoption' => '1.5.0@94e644f7d2051a5f0fcf77d81605f152eecff0ed',
  'psr/cache' => '1.0.1@d11b50ad223250cf17b86e38383413f5a6764bf8',
  'psr/container' => '1.0.0@b7ce3b176482dbbc1245ebf52b181af44c2cf55f',
  'psr/http-message' => '1.0.1@f6561bf28d520154e4b0ec72be95418abe6d9363',
  'psr/log' => '1.0.2@4ebe3a8bf773a19edfe0a84b6585ba3d401b724d',
  'ratchet/rfc6455' => '0.2.4@1612f528c3496ad06e910d0f8b6f16ab97696706',
  'react/cache' => 'v0.5.0@7d7da7fb7574d471904ba357b39bbf110ccdbf66',
  'react/dns' => 'v0.4.15@319e110a436d26a2fa137cfa3ef2063951715794',
  'react/event-loop' => 'v1.0.0@0266aff7aa7b0613b1f38a723e14a0ebc55cfca3',
  'react/promise' => 'v2.7.0@f4edc2581617431aea50430749db55cc3fc031b3',
  'react/promise-timer' => 'v1.5.0@a11206938ca2394dc7bb368f5da25cd4533fa603',
  'react/socket' => 'v1.1.0@34381d9282d12670eb56b45981aad82e033ed58f',
  'react/stream' => 'v1.0.0@fdd0140f42805d65bf9687636503db0b326d2244',
  'sensio/framework-extra-bundle' => 'v5.2.1@535b56b7b0325e87b15b9c57bd3631ae2a0b9f16',
  'stof/doctrine-extensions-bundle' => 'v1.3.0@46db71ec7ffee9122eca3cdddd4ef8d84bae269c',
  'swiftmailer/swiftmailer' => 'v6.1.3@8ddcb66ac10c392d3beb54829eef8ac1438595f4',
  'symfony/asset' => 'v4.4.0@7ec5fc653dab63d7519a6f411982ee224a696d66',
  'symfony/cache' => 'v4.4.0@72d5cdc6920f889290beb65fa96b5e9d4515e382',
  'symfony/cache-contracts' => 'v2.0.1@23ed8bfc1a4115feca942cb5f1aacdf3dcdf3c16',
  'symfony/config' => 'v4.4.0@f08e1c48e1f05d07c32f2d8599ed539e62105beb',
  'symfony/console' => 'v4.4.0@35d9077f495c6d184d9930f7a7ecbd1ad13c7ab8',
  'symfony/contracts' => 'v1.1.0@d3636025e8253c6144358ec0a62773cae588395b',
  'symfony/debug' => 'v4.4.0@b24b791f817116b29e52a63e8544884cf9a40757',
  'symfony/dependency-injection' => 'v4.4.0@d4439814135ed1343c93bde998b7792af8852e41',
  'symfony/doctrine-bridge' => 'v4.2.12@5e8d62453eda38a523a12cc918031cc8f48e4b65',
  'symfony/error-handler' => 'v4.4.0@e1acb58dc6a8722617fe56565f742bcf7e8744bf',
  'symfony/event-dispatcher' => 'v4.4.0@ab1c43e17fff802bef0a898f3bc088ac33b8e0e1',
  'symfony/event-dispatcher-contracts' => 'v1.1.7@c43ab685673fb6c8d84220c77897b1d6cdbe1d18',
  'symfony/expression-language' => 'v4.4.0@8a1028a65623a8f7bba582b60e4fd308e6f43001',
  'symfony/filesystem' => 'v4.4.0@d12b01cba60be77b583c9af660007211e3909854',
  'symfony/finder' => 'v4.4.0@ce8743441da64c41e2a667b8eb66070444ed911e',
  'symfony/flex' => 'v1.5.0@97d4d94bff1b6bd9e9c5750ddbe248185ecb588b',
  'symfony/form' => 'v4.4.0@d381d4fadee5f84ee730448ce6459604babd57ef',
  'symfony/framework-bundle' => 'v4.3.8@117560d884615d0c39179a24aa3c69c4af540d81',
  'symfony/http-client' => 'v4.4.0@233f73babb157deac7289119aa3d0e871bac8def',
  'symfony/http-client-contracts' => 'v2.0.1@378868b61b85c5cac6822d4f84e26999c9f2e881',
  'symfony/http-foundation' => 'v4.4.0@502040dd2b0cf0a292defeb6145f4d7a4753c99c',
  'symfony/http-kernel' => 'v4.4.0@5a5e7237d928aa98ff8952050cbbf0135899b6b0',
  'symfony/inflector' => 'v4.4.0@98581481d9ddabe4db3a66e10202fe1fa08d791b',
  'symfony/intl' => 'v4.4.0@299cbfd6be791438e8d93ffb25765b5b93021bf9',
  'symfony/lts' => 'dev-master@c1affae45b78aee036effa1759237e7fa96d4af2',
  'symfony/maker-bundle' => 'v1.14.3@c864e7f9b8d1e1f5f60acc3beda11299f637aded',
  'symfony/mime' => 'v5.0.0@76f3c09b7382bf979af7bcd8e6f8033f1324285e',
  'symfony/monolog-bridge' => 'v4.2.12@41b01701e23016b920638ed551c53f077daacefd',
  'symfony/monolog-bundle' => 'v3.5.0@dd80460fcfe1fa2050a7103ad818e9d0686ce6fd',
  'symfony/options-resolver' => 'v4.4.0@2be23e63f33de16b49294ea6581f462932a77e2f',
  'symfony/orm-pack' => 'v1.0.7@c57f5e05232ca40626eb9fa52a32bc8565e9231c',
  'symfony/polyfill-ctype' => 'v1.13.1@f8f0b461be3385e56d6de3dbb5a0df24c0c275e3',
  'symfony/polyfill-intl-icu' => 'v1.13.1@b3dffd68afa61ca70f2327f2dd9bbeb6aa53d70b',
  'symfony/polyfill-intl-idn' => 'v1.13.1@6f9c239e61e1b0c9229a28ff89a812dc449c3d46',
  'symfony/polyfill-mbstring' => 'v1.13.1@7b4aab9743c30be783b73de055d24a39cf4b954f',
  'symfony/polyfill-php72' => 'v1.13.1@66fea50f6cb37a35eea048d75a7d99a45b586038',
  'symfony/polyfill-php73' => 'v1.13.1@4b0e2222c55a25b4541305a053013d5647d3a25f',
  'symfony/process' => 'v4.4.0@75ad33d9b6f25325ebc396d68ad86fd74bcfbb06',
  'symfony/property-access' => 'v4.4.0@4df120cbe473d850eb59f75c341915955e45f25b',
  'symfony/routing' => 'v4.4.0@cf6d72cf0348775f5243b8389169a7096221ea40',
  'symfony/security-bundle' => 'v4.3.8@9f247c672e08385c67e3ca7cfc1484072bcc6517',
  'symfony/security-core' => 'v4.4.0@312c91f90786fd7add89e8542cfc98543f0e60db',
  'symfony/security-csrf' => 'v4.4.0@aeed1a2315019b5a090f5ad34c01f1935ea9b757',
  'symfony/security-guard' => 'v4.4.0@367e7d49648113279baddceb296ffd90c621414a',
  'symfony/security-http' => 'v4.4.0@e49361b75e9acbc029b35ae4ba957e712137286b',
  'symfony/serializer' => 'v4.4.0@57116a962eb0c5e165009535f1e1d2e7024e78de',
  'symfony/service-contracts' => 'v2.0.1@144c5e51266b281231e947b51223ba14acf1a749',
  'symfony/swiftmailer-bundle' => 'v3.2.6@7a83160b50a2479d37eb74ba71577380b9afe4f5',
  'symfony/templating' => 'v4.4.0@628e5d6b9f779721a960cbc02f129c8b02c3f514',
  'symfony/translation' => 'v4.4.0@897fb68ee7933372517b551d6f08c6d4bb0b8c40',
  'symfony/translation-contracts' => 'v1.1.7@364518c132c95642e530d9b2d217acbc2ccac3e6',
  'symfony/twig-bridge' => 'v4.2.2@bf9379a4fae77a05a2446880bc7867651e8b2a87',
  'symfony/twig-bundle' => 'v4.2.7@321d5bd0608f3cf34062c47edfe6079556f6d6f1',
  'symfony/validator' => 'v4.3.3@dbca6327b315d29653f826057ee5034ff234c587',
  'symfony/var-dumper' => 'v4.4.0@eade2890f8b0eeb279b6cf41b50a10007294490f',
  'symfony/var-exporter' => 'v5.0.0@e2f1eeb12edacf744c4b359a859204578fdf8549',
  'symfony/webpack-encore-pack' => 'v1.0.3@8d7f51379d7ae17aea7cf501d910a11896895ac4',
  'symfony/yaml' => 'v4.4.0@76de473358fe802578a415d5bb43c296cf09d211',
  'twig/extensions' => 'v1.5.2@2c1a86526d0044065220d1b51ac08348bea5ca82',
  'twig/twig' => 'v2.5.0@6a5f676b77a90823c2d4eaf76137b771adf31323',
  'vich/uploader-bundle' => '1.8.3@37bc4b3264a0e22608a56406d5019b26864b9553',
  'willdurand/hateoas' => '2.12.0@71b1af62b398dc9a870ac0b16c84bdc23a76a5c5',
  'willdurand/hateoas-bundle' => '1.4.0@d1f915fd4f8a7cd43a88a0ce97ffb28abe3a94fa',
  'willdurand/jsonp-callback-validator' => 'v1.1.0@1a7d388bb521959e612ef50c5c7b1691b097e909',
  'willdurand/negotiation' => 'v2.3.1@03436ededa67c6e83b9b12defac15384cb399dc9',
  'wisembly/elephant.io' => 'v3.3.1@9d56f409fe231a906af87005f83a135565632d3f',
  'zendframework/zend-code' => '3.3.1@c21db169075c6ec4b342149f446e7b7b724f95eb',
  'zendframework/zend-eventmanager' => '3.2.1@a5e2583a211f73604691586b8406ff7296a946dd',
  'atoum/atoum' => '3.3.0@c5279d0ecd4e2d53af6b38815db2cafee8fc46b6',
  'psr/simple-cache' => '1.0.1@408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
  'symfony/dotenv' => 'v4.4.0@1a9cad0daa3d0726124d7bec2419591ed0f03bc3',
  'symfony/profiler-pack' => 'v1.0.4@99c4370632c2a59bb0444852f92140074ef02209',
  'symfony/stopwatch' => 'v4.4.0@5745b514fc56ae1907c6b8ed74f94f90f64694e9',
  'symfony/web-profiler-bundle' => 'v4.2.8@f4c054dad30b46f23aae60ecfedacc08462c47ef',
  'symfony/web-server-bundle' => 'v4.4.0@83202a9dae60b29eb55ae1a0c6696c586de3ce0b',
  'symfony/polyfill-apcu' => '*@f64a174f0418d28524fb85a9013be3612101203c',
  'symfony/polyfill-php70' => '*@f64a174f0418d28524fb85a9013be3612101203c',
  'symfony/polyfill-php56' => '*@f64a174f0418d28524fb85a9013be3612101203c',
  '__root__' => '2019.9999999.9999999.9999999-dev@f64a174f0418d28524fb85a9013be3612101203c',
);

    private function __construct()
    {
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    public static function getVersion(string $packageName) : string
    {
        if (isset(self::VERSIONS[$packageName])) {
            return self::VERSIONS[$packageName];
        }

        throw new \OutOfBoundsException(
            'Required package "' . $packageName . '" is not installed: cannot detect its version'
        );
    }
}
