<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit065ced53282fa1d1adde9432547fbbc5
{
    public static $files = array (
        '320cde22f66dd4f5d3fd621d3e88b98f' => __DIR__ . '/..' . '/symfony/polyfill-ctype/bootstrap.php',
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        '0d59ee240a4cd96ddbb4ff164fccea4d' => __DIR__ . '/..' . '/symfony/polyfill-php73/bootstrap.php',
        '25072dd6e2470089de65ae7bf11d3109' => __DIR__ . '/..' . '/symfony/polyfill-php72/bootstrap.php',
        '667aeda72477189d0494fecd327c3641' => __DIR__ . '/..' . '/symfony/var-dumper/Resources/functions/dump.php',
        'f598d06aa772fa33d905e87be6398fb1' => __DIR__ . '/..' . '/symfony/polyfill-intl-idn/bootstrap.php',
        '6a47392539ca2329373e0d33e1dba053' => __DIR__ . '/..' . '/symfony/polyfill-intl-icu/bootstrap.php',
        'ad155f8f1cf0d418fe49e248db8c661b' => __DIR__ . '/..' . '/react/promise/src/functions_include.php',
        '2c102faa651ef8ea5874edb585946bce' => __DIR__ . '/..' . '/swiftmailer/swiftmailer/lib/swift_required.php',
        '6b06ce8ccf69c43a60a1e48495a034c9' => __DIR__ . '/..' . '/react/promise-timer/src/functions.php',
        'a0edc8309cc5e1d60e3047b5df6b7052' => __DIR__ . '/..' . '/guzzlehttp/psr7/src/functions_include.php',
    );

    public static $prefixLengthsPsr4 = array (
        'Z' => 
        array (
            'Zend\\EventManager\\' => 18,
            'Zend\\Code\\' => 10,
        ),
        'V' => 
        array (
            'Vich\\UploaderBundle\\' => 20,
        ),
        'T' => 
        array (
            'Twig\\Extensions\\' => 16,
            'Twig\\' => 5,
        ),
        'S' => 
        array (
            'Symfony\\Polyfill\\Php73\\' => 23,
            'Symfony\\Polyfill\\Php72\\' => 23,
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Polyfill\\Intl\\Idn\\' => 26,
            'Symfony\\Polyfill\\Ctype\\' => 23,
            'Symfony\\Flex\\' => 13,
            'Symfony\\Contracts\\Translation\\' => 30,
            'Symfony\\Contracts\\Service\\' => 26,
            'Symfony\\Contracts\\HttpClient\\' => 29,
            'Symfony\\Contracts\\EventDispatcher\\' => 34,
            'Symfony\\Contracts\\Cache\\' => 24,
            'Symfony\\Contracts\\' => 18,
            'Symfony\\Component\\Yaml\\' => 23,
            'Symfony\\Component\\VarExporter\\' => 30,
            'Symfony\\Component\\VarDumper\\' => 28,
            'Symfony\\Component\\Validator\\' => 28,
            'Symfony\\Component\\Translation\\' => 30,
            'Symfony\\Component\\Templating\\' => 29,
            'Symfony\\Component\\Stopwatch\\' => 28,
            'Symfony\\Component\\Serializer\\' => 29,
            'Symfony\\Component\\Security\\Http\\' => 32,
            'Symfony\\Component\\Security\\Guard\\' => 33,
            'Symfony\\Component\\Security\\Csrf\\' => 32,
            'Symfony\\Component\\Security\\Core\\' => 32,
            'Symfony\\Component\\Routing\\' => 26,
            'Symfony\\Component\\PropertyAccess\\' => 33,
            'Symfony\\Component\\Process\\' => 26,
            'Symfony\\Component\\OptionsResolver\\' => 34,
            'Symfony\\Component\\Mime\\' => 23,
            'Symfony\\Component\\Intl\\' => 23,
            'Symfony\\Component\\Inflector\\' => 28,
            'Symfony\\Component\\HttpKernel\\' => 29,
            'Symfony\\Component\\HttpFoundation\\' => 33,
            'Symfony\\Component\\HttpClient\\' => 29,
            'Symfony\\Component\\Form\\' => 23,
            'Symfony\\Component\\Finder\\' => 25,
            'Symfony\\Component\\Filesystem\\' => 29,
            'Symfony\\Component\\ExpressionLanguage\\' => 37,
            'Symfony\\Component\\EventDispatcher\\' => 34,
            'Symfony\\Component\\ErrorHandler\\' => 31,
            'Symfony\\Component\\Dotenv\\' => 25,
            'Symfony\\Component\\DependencyInjection\\' => 38,
            'Symfony\\Component\\Debug\\' => 24,
            'Symfony\\Component\\Console\\' => 26,
            'Symfony\\Component\\Config\\' => 25,
            'Symfony\\Component\\Cache\\' => 24,
            'Symfony\\Component\\Asset\\' => 24,
            'Symfony\\Bundle\\WebServerBundle\\' => 31,
            'Symfony\\Bundle\\WebProfilerBundle\\' => 33,
            'Symfony\\Bundle\\TwigBundle\\' => 26,
            'Symfony\\Bundle\\SwiftmailerBundle\\' => 33,
            'Symfony\\Bundle\\SecurityBundle\\' => 30,
            'Symfony\\Bundle\\MonologBundle\\' => 29,
            'Symfony\\Bundle\\MakerBundle\\' => 27,
            'Symfony\\Bundle\\FrameworkBundle\\' => 31,
            'Symfony\\Bridge\\Twig\\' => 20,
            'Symfony\\Bridge\\Monolog\\' => 23,
            'Symfony\\Bridge\\Doctrine\\' => 24,
            'Stof\\DoctrineExtensionsBundle\\' => 30,
            'Sensio\\Bundle\\FrameworkExtraBundle\\' => 35,
        ),
        'R' => 
        array (
            'React\\Stream\\' => 13,
            'React\\Socket\\' => 13,
            'React\\Promise\\Timer\\' => 20,
            'React\\Promise\\' => 14,
            'React\\EventLoop\\' => 16,
            'React\\Dns\\' => 10,
            'React\\Cache\\' => 12,
            'Ratchet\\RFC6455\\' => 16,
            'Ratchet\\' => 8,
        ),
        'P' => 
        array (
            'Psr\\SimpleCache\\' => 16,
            'Psr\\Log\\' => 8,
            'Psr\\Http\\Message\\' => 17,
            'Psr\\Container\\' => 14,
            'Psr\\Cache\\' => 10,
            'PhpParser\\' => 10,
            'PackageVersions\\' => 16,
        ),
        'N' => 
        array (
            'Negotiation\\' => 12,
            'Namshi\\JOSE\\' => 12,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
        ),
        'L' => 
        array (
            'Lexik\\Bundle\\JWTAuthenticationBundle\\' => 37,
            'Lcobucci\\JWT\\' => 13,
        ),
        'K' => 
        array (
            'Knp\\Snappy\\' => 11,
            'Knp\\Bundle\\SnappyBundle\\' => 24,
        ),
        'J' => 
        array (
            'JMS\\SerializerBundle\\' => 21,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Psr7\\' => 16,
            'Gedmo\\' => 6,
        ),
        'F' => 
        array (
            'FOS\\RestBundle\\' => 15,
        ),
        'E' => 
        array (
            'ElephantIO\\' => 11,
            'Egulias\\EmailValidator\\' => 23,
        ),
        'D' => 
        array (
            'Doctrine\\ORM\\' => 13,
            'Doctrine\\Migrations\\' => 20,
            'Doctrine\\Instantiator\\' => 22,
            'Doctrine\\DBAL\\Migrations\\' => 25,
            'Doctrine\\Common\\Inflector\\' => 26,
            'Doctrine\\Common\\Cache\\' => 22,
            'Doctrine\\Common\\Annotations\\' => 28,
            'Doctrine\\Common\\' => 16,
            'Doctrine\\Bundle\\MigrationsBundle\\' => 33,
            'Doctrine\\Bundle\\DoctrineCacheBundle\\' => 36,
            'Doctrine\\Bundle\\DoctrineBundle\\' => 31,
        ),
        'B' => 
        array (
            'Bazinga\\Bundle\\HateoasBundle\\' => 29,
        ),
        'A' => 
        array (
            'App\\Tests\\' => 10,
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Zend\\EventManager\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-eventmanager/src',
        ),
        'Zend\\Code\\' => 
        array (
            0 => __DIR__ . '/..' . '/zendframework/zend-code/src',
        ),
        'Vich\\UploaderBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/vich/uploader-bundle',
        ),
        'Twig\\Extensions\\' => 
        array (
            0 => __DIR__ . '/..' . '/twig/extensions/src',
        ),
        'Twig\\' => 
        array (
            0 => __DIR__ . '/..' . '/twig/twig/src',
        ),
        'Symfony\\Polyfill\\Php73\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php73',
        ),
        'Symfony\\Polyfill\\Php72\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php72',
        ),
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Polyfill\\Intl\\Idn\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-intl-idn',
        ),
        'Symfony\\Polyfill\\Ctype\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-ctype',
        ),
        'Symfony\\Flex\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/flex/src',
        ),
        'Symfony\\Contracts\\Translation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/translation-contracts',
        ),
        'Symfony\\Contracts\\Service\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/service-contracts',
        ),
        'Symfony\\Contracts\\HttpClient\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-client-contracts',
        ),
        'Symfony\\Contracts\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/event-dispatcher-contracts',
        ),
        'Symfony\\Contracts\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/cache-contracts',
        ),
        'Symfony\\Contracts\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/contracts',
        ),
        'Symfony\\Component\\Yaml\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/yaml',
        ),
        'Symfony\\Component\\VarExporter\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/var-exporter',
        ),
        'Symfony\\Component\\VarDumper\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/var-dumper',
        ),
        'Symfony\\Component\\Validator\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/validator',
        ),
        'Symfony\\Component\\Translation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/translation',
        ),
        'Symfony\\Component\\Templating\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/templating',
        ),
        'Symfony\\Component\\Stopwatch\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/stopwatch',
        ),
        'Symfony\\Component\\Serializer\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/serializer',
        ),
        'Symfony\\Component\\Security\\Http\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/security-http',
        ),
        'Symfony\\Component\\Security\\Guard\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/security-guard',
        ),
        'Symfony\\Component\\Security\\Csrf\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/security-csrf',
        ),
        'Symfony\\Component\\Security\\Core\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/security-core',
        ),
        'Symfony\\Component\\Routing\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/routing',
        ),
        'Symfony\\Component\\PropertyAccess\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/property-access',
        ),
        'Symfony\\Component\\Process\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/process',
        ),
        'Symfony\\Component\\OptionsResolver\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/options-resolver',
        ),
        'Symfony\\Component\\Mime\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/mime',
        ),
        'Symfony\\Component\\Intl\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/intl',
        ),
        'Symfony\\Component\\Inflector\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/inflector',
        ),
        'Symfony\\Component\\HttpKernel\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-kernel',
        ),
        'Symfony\\Component\\HttpFoundation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-foundation',
        ),
        'Symfony\\Component\\HttpClient\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-client',
        ),
        'Symfony\\Component\\Form\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/form',
        ),
        'Symfony\\Component\\Finder\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/finder',
        ),
        'Symfony\\Component\\Filesystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/filesystem',
        ),
        'Symfony\\Component\\ExpressionLanguage\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/expression-language',
        ),
        'Symfony\\Component\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/event-dispatcher',
        ),
        'Symfony\\Component\\ErrorHandler\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/error-handler',
        ),
        'Symfony\\Component\\Dotenv\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/dotenv',
        ),
        'Symfony\\Component\\DependencyInjection\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/dependency-injection',
        ),
        'Symfony\\Component\\Debug\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/debug',
        ),
        'Symfony\\Component\\Console\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/console',
        ),
        'Symfony\\Component\\Config\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/config',
        ),
        'Symfony\\Component\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/cache',
        ),
        'Symfony\\Component\\Asset\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/asset',
        ),
        'Symfony\\Bundle\\WebServerBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/web-server-bundle',
        ),
        'Symfony\\Bundle\\WebProfilerBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/web-profiler-bundle',
        ),
        'Symfony\\Bundle\\TwigBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/twig-bundle',
        ),
        'Symfony\\Bundle\\SwiftmailerBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/swiftmailer-bundle',
        ),
        'Symfony\\Bundle\\SecurityBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/security-bundle',
        ),
        'Symfony\\Bundle\\MonologBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/monolog-bundle',
        ),
        'Symfony\\Bundle\\MakerBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/maker-bundle/src',
        ),
        'Symfony\\Bundle\\FrameworkBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/framework-bundle',
        ),
        'Symfony\\Bridge\\Twig\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/twig-bridge',
        ),
        'Symfony\\Bridge\\Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/monolog-bridge',
        ),
        'Symfony\\Bridge\\Doctrine\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/doctrine-bridge',
        ),
        'Stof\\DoctrineExtensionsBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/stof/doctrine-extensions-bundle',
        ),
        'Sensio\\Bundle\\FrameworkExtraBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/sensio/framework-extra-bundle',
        ),
        'React\\Stream\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/stream/src',
        ),
        'React\\Socket\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/socket/src',
        ),
        'React\\Promise\\Timer\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/promise-timer/src',
        ),
        'React\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/promise/src',
        ),
        'React\\EventLoop\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/event-loop/src',
        ),
        'React\\Dns\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/dns/src',
        ),
        'React\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/react/cache/src',
        ),
        'Ratchet\\RFC6455\\' => 
        array (
            0 => __DIR__ . '/..' . '/ratchet/rfc6455/src',
        ),
        'Ratchet\\' => 
        array (
            0 => __DIR__ . '/..' . '/cboden/ratchet/src/Ratchet',
        ),
        'Psr\\SimpleCache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/simple-cache/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'Psr\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
        'PhpParser\\' => 
        array (
            0 => __DIR__ . '/..' . '/nikic/php-parser/lib/PhpParser',
        ),
        'PackageVersions\\' => 
        array (
            0 => __DIR__ . '/..' . '/ocramius/package-versions/src/PackageVersions',
        ),
        'Negotiation\\' => 
        array (
            0 => __DIR__ . '/..' . '/willdurand/negotiation/src/Negotiation',
        ),
        'Namshi\\JOSE\\' => 
        array (
            0 => __DIR__ . '/..' . '/namshi/jose/src/Namshi/JOSE',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
        'Lexik\\Bundle\\JWTAuthenticationBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/lexik/jwt-authentication-bundle',
        ),
        'Lcobucci\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/lcobucci/jwt/src',
        ),
        'Knp\\Snappy\\' => 
        array (
            0 => __DIR__ . '/..' . '/knplabs/knp-snappy/src/Knp/Snappy',
        ),
        'Knp\\Bundle\\SnappyBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/knplabs/knp-snappy-bundle',
        ),
        'JMS\\SerializerBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/jms/serializer-bundle',
        ),
        'GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'Gedmo\\' => 
        array (
            0 => __DIR__ . '/..' . '/gedmo/doctrine-extensions/lib/Gedmo',
        ),
        'FOS\\RestBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/friendsofsymfony/rest-bundle',
        ),
        'ElephantIO\\' => 
        array (
            0 => __DIR__ . '/..' . '/wisembly/elephant.io/src',
            1 => __DIR__ . '/..' . '/wisembly/elephant.io/test',
        ),
        'Egulias\\EmailValidator\\' => 
        array (
            0 => __DIR__ . '/..' . '/egulias/email-validator/EmailValidator',
        ),
        'Doctrine\\ORM\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/orm/lib/Doctrine/ORM',
        ),
        'Doctrine\\Migrations\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/migrations/lib/Doctrine/Migrations',
        ),
        'Doctrine\\Instantiator\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/instantiator/src/Doctrine/Instantiator',
        ),
        'Doctrine\\DBAL\\Migrations\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/migrations/lib/Doctrine/DBAL/Migrations',
        ),
        'Doctrine\\Common\\Inflector\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/inflector/lib/Doctrine/Common/Inflector',
        ),
        'Doctrine\\Common\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/cache/lib/Doctrine/Common/Cache',
        ),
        'Doctrine\\Common\\Annotations\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/annotations/lib/Doctrine/Common/Annotations',
        ),
        'Doctrine\\Common\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/reflection/lib/Doctrine/Common',
            1 => __DIR__ . '/..' . '/doctrine/event-manager/lib/Doctrine/Common',
            2 => __DIR__ . '/..' . '/doctrine/persistence/lib/Doctrine/Common',
            3 => __DIR__ . '/..' . '/doctrine/common/lib/Doctrine/Common',
        ),
        'Doctrine\\Bundle\\MigrationsBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/doctrine-migrations-bundle',
        ),
        'Doctrine\\Bundle\\DoctrineCacheBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/doctrine-cache-bundle',
        ),
        'Doctrine\\Bundle\\DoctrineBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/doctrine-bundle',
        ),
        'Bazinga\\Bundle\\HateoasBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/willdurand/hateoas-bundle',
        ),
        'App\\Tests\\' => 
        array (
            0 => __DIR__ . '/../..' . '/tests',
        ),
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'T' => 
        array (
            'Twig_Extensions_' => 
            array (
                0 => __DIR__ . '/..' . '/twig/extensions/lib',
            ),
            'Twig_' => 
            array (
                0 => __DIR__ . '/..' . '/twig/twig/lib',
            ),
        ),
        'P' => 
        array (
            'ProxyManager\\' => 
            array (
                0 => __DIR__ . '/..' . '/ocramius/proxy-manager/src',
            ),
            'PhpOption\\' => 
            array (
                0 => __DIR__ . '/..' . '/phpoption/phpoption/src',
            ),
            'PhpCollection' => 
            array (
                0 => __DIR__ . '/..' . '/phpcollection/phpcollection/src',
            ),
        ),
        'M' => 
        array (
            'Metadata\\' => 
            array (
                0 => __DIR__ . '/..' . '/jms/metadata/src',
            ),
        ),
        'J' => 
        array (
            'JsonpCallbackValidator' => 
            array (
                0 => __DIR__ . '/..' . '/willdurand/jsonp-callback-validator/src',
            ),
            'JMS\\Serializer' => 
            array (
                0 => __DIR__ . '/..' . '/jms/serializer/src',
            ),
            'JMS\\' => 
            array (
                0 => __DIR__ . '/..' . '/jms/parser-lib/src',
            ),
        ),
        'H' => 
        array (
            'Hateoas' => 
            array (
                0 => __DIR__ . '/..' . '/willdurand/hateoas/src',
            ),
        ),
        'E' => 
        array (
            'Evenement' => 
            array (
                0 => __DIR__ . '/..' . '/evenement/evenement/src',
            ),
        ),
        'D' => 
        array (
            'Doctrine\\DBAL\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/dbal/lib',
            ),
            'Doctrine\\Common\\Lexer\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/lexer/lib',
            ),
            'Doctrine\\Common\\Collections\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/collections/lib',
            ),
        ),
        'C' => 
        array (
            'Curl' => 
            array (
                0 => __DIR__ . '/..' . '/curl/curl/src',
            ),
        ),
        'B' => 
        array (
            'Behat\\Transliterator' => 
            array (
                0 => __DIR__ . '/..' . '/behat/transliterator/src',
            ),
        ),
    );

    public static $classMap = array (
        'Collator' => __DIR__ . '/..' . '/symfony/intl/Resources/stubs/Collator.php',
        'IntlDateFormatter' => __DIR__ . '/..' . '/symfony/intl/Resources/stubs/IntlDateFormatter.php',
        'JsonException' => __DIR__ . '/..' . '/symfony/polyfill-php73/Resources/stubs/JsonException.php',
        'Locale' => __DIR__ . '/..' . '/symfony/intl/Resources/stubs/Locale.php',
        'NumberFormatter' => __DIR__ . '/..' . '/symfony/intl/Resources/stubs/NumberFormatter.php',
        'SqlFormatter' => __DIR__ . '/..' . '/jdorn/sql-formatter/lib/SqlFormatter.php',
        'mageekguy\\atoum\\adapter' => __DIR__ . '/..' . '/atoum/atoum/classes/adapter.php',
        'mageekguy\\atoum\\adapter\\definition' => __DIR__ . '/..' . '/atoum/atoum/classes/adapter/definition.php',
        'mageekguy\\atoum\\annotations\\extractor' => __DIR__ . '/..' . '/atoum/atoum/classes/annotations/extractor.php',
        'mageekguy\\atoum\\asserter' => __DIR__ . '/..' . '/atoum/atoum/classes/asserter.php',
        'mageekguy\\atoum\\asserter\\definition' => __DIR__ . '/..' . '/atoum/atoum/classes/asserter/definition.php',
        'mageekguy\\atoum\\asserter\\exception' => __DIR__ . '/..' . '/atoum/atoum/classes/asserter/exception.php',
        'mageekguy\\atoum\\asserter\\generator' => __DIR__ . '/..' . '/atoum/atoum/classes/asserter/generator.php',
        'mageekguy\\atoum\\asserter\\resolver' => __DIR__ . '/..' . '/atoum/atoum/classes/asserter/resolver.php',
        'mageekguy\\atoum\\asserters\\adapter' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/adapter.php',
        'mageekguy\\atoum\\asserters\\adapter\\call' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/adapter/call.php',
        'mageekguy\\atoum\\asserters\\adapter\\call\\exceptions\\logic' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/adapter/call/exceptions/logic.php',
        'mageekguy\\atoum\\asserters\\adapter\\call\\manager' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/adapter/call/manager.php',
        'mageekguy\\atoum\\asserters\\adapter\\call\\manager\\exception' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/adapter/call/manager/exception.php',
        'mageekguy\\atoum\\asserters\\adapter\\exceptions\\logic' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/adapter/exceptions/logic.php',
        'mageekguy\\atoum\\asserters\\boolean' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/boolean.php',
        'mageekguy\\atoum\\asserters\\castToArray' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/castToArray.php',
        'mageekguy\\atoum\\asserters\\castToString' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/castToString.php',
        'mageekguy\\atoum\\asserters\\constant' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/constant.php',
        'mageekguy\\atoum\\asserters\\dateInterval' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/dateInterval.php',
        'mageekguy\\atoum\\asserters\\dateTime' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/dateTime.php',
        'mageekguy\\atoum\\asserters\\error' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/error.php',
        'mageekguy\\atoum\\asserters\\exception' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/exception.php',
        'mageekguy\\atoum\\asserters\\extension' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/extension.php',
        'mageekguy\\atoum\\asserters\\generator' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/generator.php',
        'mageekguy\\atoum\\asserters\\generator\\asserterProxy' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/generator/asserterProxy.php',
        'mageekguy\\atoum\\asserters\\hash' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/hash.php',
        'mageekguy\\atoum\\asserters\\integer' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/integer.php',
        'mageekguy\\atoum\\asserters\\iterator' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/iterator.php',
        'mageekguy\\atoum\\asserters\\mock' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/mock.php',
        'mageekguy\\atoum\\asserters\\mock\\exceptions\\logic' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/mock/exceptions/logic.php',
        'mageekguy\\atoum\\asserters\\mysqlDateTime' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/mysqlDateTime.php',
        'mageekguy\\atoum\\asserters\\output' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/output.php',
        'mageekguy\\atoum\\asserters\\phpArray' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/phpArray.php',
        'mageekguy\\atoum\\asserters\\phpArray\\child' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/phpArray/child.php',
        'mageekguy\\atoum\\asserters\\phpClass' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/phpClass.php',
        'mageekguy\\atoum\\asserters\\phpFloat' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/phpFloat.php',
        'mageekguy\\atoum\\asserters\\phpFunction' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/phpFunction.php',
        'mageekguy\\atoum\\asserters\\phpObject' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/phpObject.php',
        'mageekguy\\atoum\\asserters\\phpResource' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/phpResource.php',
        'mageekguy\\atoum\\asserters\\phpString' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/phpString.php',
        'mageekguy\\atoum\\asserters\\sizeOf' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/sizeOf.php',
        'mageekguy\\atoum\\asserters\\stream' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/stream.php',
        'mageekguy\\atoum\\asserters\\testedClass' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/testedClass.php',
        'mageekguy\\atoum\\asserters\\utf8String' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/utf8String.php',
        'mageekguy\\atoum\\asserters\\variable' => __DIR__ . '/..' . '/atoum/atoum/classes/asserters/variable.php',
        'mageekguy\\atoum\\autoloader' => __DIR__ . '/..' . '/atoum/atoum/classes/autoloader.php',
        'mageekguy\\atoum\\autoloader\\mock' => __DIR__ . '/..' . '/atoum/atoum/classes/autoloader/mock.php',
        'mageekguy\\atoum\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/cli.php',
        'mageekguy\\atoum\\cli\\clear' => __DIR__ . '/..' . '/atoum/atoum/classes/cli/clear.php',
        'mageekguy\\atoum\\cli\\colorizer' => __DIR__ . '/..' . '/atoum/atoum/classes/cli/colorizer.php',
        'mageekguy\\atoum\\cli\\command' => __DIR__ . '/..' . '/atoum/atoum/classes/cli/command.php',
        'mageekguy\\atoum\\cli\\command\\exception' => __DIR__ . '/..' . '/atoum/atoum/classes/cli/command/exception.php',
        'mageekguy\\atoum\\cli\\commands\\git' => __DIR__ . '/..' . '/atoum/atoum/classes/cli/commands/git.php',
        'mageekguy\\atoum\\cli\\progressBar' => __DIR__ . '/..' . '/atoum/atoum/classes/cli/progressBar.php',
        'mageekguy\\atoum\\cli\\progressBar\\dot' => __DIR__ . '/..' . '/atoum/atoum/classes/cli/progressBar/dot.php',
        'mageekguy\\atoum\\cli\\prompt' => __DIR__ . '/..' . '/atoum/atoum/classes/cli/prompt.php',
        'mageekguy\\atoum\\configurator' => __DIR__ . '/..' . '/atoum/atoum/classes/configurator.php',
        'mageekguy\\atoum\\exception' => __DIR__ . '/..' . '/atoum/atoum/classes/exception.php',
        'mageekguy\\atoum\\exceptions\\logic' => __DIR__ . '/..' . '/atoum/atoum/classes/exceptions/logic.php',
        'mageekguy\\atoum\\exceptions\\logic\\badMethodCall' => __DIR__ . '/..' . '/atoum/atoum/classes/exceptions/logic/badMethodCall.php',
        'mageekguy\\atoum\\exceptions\\logic\\invalidArgument' => __DIR__ . '/..' . '/atoum/atoum/classes/exceptions/logic/invalidArgument.php',
        'mageekguy\\atoum\\exceptions\\runtime' => __DIR__ . '/..' . '/atoum/atoum/classes/exceptions/runtime.php',
        'mageekguy\\atoum\\exceptions\\runtime\\file' => __DIR__ . '/..' . '/atoum/atoum/classes/exceptions/runtime/file.php',
        'mageekguy\\atoum\\exceptions\\runtime\\unexpectedValue' => __DIR__ . '/..' . '/atoum/atoum/classes/exceptions/runtime/unexpectedValue.php',
        'mageekguy\\atoum\\extension' => __DIR__ . '/..' . '/atoum/atoum/classes/extension.php',
        'mageekguy\\atoum\\extension\\aggregator' => __DIR__ . '/..' . '/atoum/atoum/classes/extension/aggregator.php',
        'mageekguy\\atoum\\extension\\configuration' => __DIR__ . '/..' . '/atoum/atoum/classes/extension/configuration.php',
        'mageekguy\\atoum\\factory\\builder' => __DIR__ . '/..' . '/atoum/atoum/classes/factory/builder.php',
        'mageekguy\\atoum\\factory\\builder\\closure' => __DIR__ . '/..' . '/atoum/atoum/classes/factory/builder/closure.php',
        'mageekguy\\atoum\\fs\\path' => __DIR__ . '/..' . '/atoum/atoum/classes/fs/path.php',
        'mageekguy\\atoum\\fs\\path\\exception' => __DIR__ . '/..' . '/atoum/atoum/classes/fs/path/exception.php',
        'mageekguy\\atoum\\fs\\path\\factory' => __DIR__ . '/..' . '/atoum/atoum/classes/fs/path/factory.php',
        'mageekguy\\atoum\\includer' => __DIR__ . '/..' . '/atoum/atoum/classes/includer.php',
        'mageekguy\\atoum\\includer\\exception' => __DIR__ . '/..' . '/atoum/atoum/classes/includer/exception.php',
        'mageekguy\\atoum\\iterators\\filters\\recursives\\atoum\\source' => __DIR__ . '/..' . '/atoum/atoum/classes/iterators/filters/recursives/atoum/source.php',
        'mageekguy\\atoum\\iterators\\filters\\recursives\\closure' => __DIR__ . '/..' . '/atoum/atoum/classes/iterators/filters/recursives/closure.php',
        'mageekguy\\atoum\\iterators\\filters\\recursives\\dot' => __DIR__ . '/..' . '/atoum/atoum/classes/iterators/filters/recursives/dot.php',
        'mageekguy\\atoum\\iterators\\filters\\recursives\\extension' => __DIR__ . '/..' . '/atoum/atoum/classes/iterators/filters/recursives/extension.php',
        'mageekguy\\atoum\\iterators\\recursives\\atoum\\source' => __DIR__ . '/..' . '/atoum/atoum/classes/iterators/recursives/atoum/source.php',
        'mageekguy\\atoum\\iterators\\recursives\\directory\\factory' => __DIR__ . '/..' . '/atoum/atoum/classes/iterators/recursives/directory/factory.php',
        'mageekguy\\atoum\\locale' => __DIR__ . '/..' . '/atoum/atoum/classes/locale.php',
        'mageekguy\\atoum\\mailer' => __DIR__ . '/..' . '/atoum/atoum/classes/mailer.php',
        'mageekguy\\atoum\\mailers\\mail' => __DIR__ . '/..' . '/atoum/atoum/classes/mailers/mail.php',
        'mageekguy\\atoum\\mock\\aggregator' => __DIR__ . '/..' . '/atoum/atoum/classes/mock/aggregator.php',
        'mageekguy\\atoum\\mock\\controller' => __DIR__ . '/..' . '/atoum/atoum/classes/mock/controller.php',
        'mageekguy\\atoum\\mock\\controller\\invoker' => __DIR__ . '/..' . '/atoum/atoum/classes/mock/controller/invoker.php',
        'mageekguy\\atoum\\mock\\controller\\iterator' => __DIR__ . '/..' . '/atoum/atoum/classes/mock/controller/iterator.php',
        'mageekguy\\atoum\\mock\\controller\\linker' => __DIR__ . '/..' . '/atoum/atoum/classes/mock/controller/linker.php',
        'mageekguy\\atoum\\mock\\generator' => __DIR__ . '/..' . '/atoum/atoum/classes/mock/generator.php',
        'mageekguy\\atoum\\mock\\generator\\method\\exception' => __DIR__ . '/..' . '/atoum/atoum/classes/mock/generator/method/exception.php',
        'mageekguy\\atoum\\mock\\php\\method' => __DIR__ . '/..' . '/atoum/atoum/classes/mock/php/method.php',
        'mageekguy\\atoum\\mock\\php\\method\\argument' => __DIR__ . '/..' . '/atoum/atoum/classes/mock/php/method/argument.php',
        'mageekguy\\atoum\\mock\\stream' => __DIR__ . '/..' . '/atoum/atoum/classes/mock/stream.php',
        'mageekguy\\atoum\\mock\\stream\\controller' => __DIR__ . '/..' . '/atoum/atoum/classes/mock/stream/controller.php',
        'mageekguy\\atoum\\mock\\stream\\invoker' => __DIR__ . '/..' . '/atoum/atoum/classes/mock/stream/invoker.php',
        'mageekguy\\atoum\\mock\\streams\\fs\\controller' => __DIR__ . '/..' . '/atoum/atoum/classes/mock/streams/fs/controller.php',
        'mageekguy\\atoum\\mock\\streams\\fs\\controller\\factory' => __DIR__ . '/..' . '/atoum/atoum/classes/mock/streams/fs/controller/factory.php',
        'mageekguy\\atoum\\mock\\streams\\fs\\directory' => __DIR__ . '/..' . '/atoum/atoum/classes/mock/streams/fs/directory.php',
        'mageekguy\\atoum\\mock\\streams\\fs\\directory\\controller' => __DIR__ . '/..' . '/atoum/atoum/classes/mock/streams/fs/directory/controller.php',
        'mageekguy\\atoum\\mock\\streams\\fs\\file' => __DIR__ . '/..' . '/atoum/atoum/classes/mock/streams/fs/file.php',
        'mageekguy\\atoum\\mock\\streams\\fs\\file\\controller' => __DIR__ . '/..' . '/atoum/atoum/classes/mock/streams/fs/file/controller.php',
        'mageekguy\\atoum\\observable' => __DIR__ . '/..' . '/atoum/atoum/classes/observable.php',
        'mageekguy\\atoum\\observer' => __DIR__ . '/..' . '/atoum/atoum/classes/observer.php',
        'mageekguy\\atoum\\observers\\runner' => __DIR__ . '/..' . '/atoum/atoum/classes/observers/runner.php',
        'mageekguy\\atoum\\observers\\test' => __DIR__ . '/..' . '/atoum/atoum/classes/observers/test.php',
        'mageekguy\\atoum\\php' => __DIR__ . '/..' . '/atoum/atoum/classes/php.php',
        'mageekguy\\atoum\\php\\call' => __DIR__ . '/..' . '/atoum/atoum/classes/php/call.php',
        'mageekguy\\atoum\\php\\exception' => __DIR__ . '/..' . '/atoum/atoum/classes/php/exception.php',
        'mageekguy\\atoum\\php\\extension' => __DIR__ . '/..' . '/atoum/atoum/classes/php/extension.php',
        'mageekguy\\atoum\\php\\mocker' => __DIR__ . '/..' . '/atoum/atoum/classes/php/mocker.php',
        'mageekguy\\atoum\\php\\mocker\\adapter' => __DIR__ . '/..' . '/atoum/atoum/classes/php/mocker/adapter.php',
        'mageekguy\\atoum\\php\\mocker\\adapter\\invoker' => __DIR__ . '/..' . '/atoum/atoum/classes/php/mocker/adapter/invoker.php',
        'mageekguy\\atoum\\php\\mocker\\constant' => __DIR__ . '/..' . '/atoum/atoum/classes/php/mocker/constant.php',
        'mageekguy\\atoum\\php\\mocker\\exception' => __DIR__ . '/..' . '/atoum/atoum/classes/php/mocker/exception.php',
        'mageekguy\\atoum\\php\\mocker\\exceptions\\constant' => __DIR__ . '/..' . '/atoum/atoum/classes/php/mocker/exceptions/constant.php',
        'mageekguy\\atoum\\php\\mocker\\funktion' => __DIR__ . '/..' . '/atoum/atoum/classes/php/mocker/funktion.php',
        'mageekguy\\atoum\\php\\tokenizer' => __DIR__ . '/..' . '/atoum/atoum/classes/php/tokenizer.php',
        'mageekguy\\atoum\\php\\tokenizer\\iterator' => __DIR__ . '/..' . '/atoum/atoum/classes/php/tokenizer/iterator.php',
        'mageekguy\\atoum\\php\\tokenizer\\iterator\\value' => __DIR__ . '/..' . '/atoum/atoum/classes/php/tokenizer/iterator/value.php',
        'mageekguy\\atoum\\php\\tokenizer\\iterators\\phpArgument' => __DIR__ . '/..' . '/atoum/atoum/classes/php/tokenizer/iterators/phpArgument.php',
        'mageekguy\\atoum\\php\\tokenizer\\iterators\\phpClass' => __DIR__ . '/..' . '/atoum/atoum/classes/php/tokenizer/iterators/phpClass.php',
        'mageekguy\\atoum\\php\\tokenizer\\iterators\\phpConstant' => __DIR__ . '/..' . '/atoum/atoum/classes/php/tokenizer/iterators/phpConstant.php',
        'mageekguy\\atoum\\php\\tokenizer\\iterators\\phpDefaultValue' => __DIR__ . '/..' . '/atoum/atoum/classes/php/tokenizer/iterators/phpDefaultValue.php',
        'mageekguy\\atoum\\php\\tokenizer\\iterators\\phpFunction' => __DIR__ . '/..' . '/atoum/atoum/classes/php/tokenizer/iterators/phpFunction.php',
        'mageekguy\\atoum\\php\\tokenizer\\iterators\\phpImportation' => __DIR__ . '/..' . '/atoum/atoum/classes/php/tokenizer/iterators/phpImportation.php',
        'mageekguy\\atoum\\php\\tokenizer\\iterators\\phpMethod' => __DIR__ . '/..' . '/atoum/atoum/classes/php/tokenizer/iterators/phpMethod.php',
        'mageekguy\\atoum\\php\\tokenizer\\iterators\\phpNamespace' => __DIR__ . '/..' . '/atoum/atoum/classes/php/tokenizer/iterators/phpNamespace.php',
        'mageekguy\\atoum\\php\\tokenizer\\iterators\\phpProperty' => __DIR__ . '/..' . '/atoum/atoum/classes/php/tokenizer/iterators/phpProperty.php',
        'mageekguy\\atoum\\php\\tokenizer\\iterators\\phpScript' => __DIR__ . '/..' . '/atoum/atoum/classes/php/tokenizer/iterators/phpScript.php',
        'mageekguy\\atoum\\php\\tokenizer\\token' => __DIR__ . '/..' . '/atoum/atoum/classes/php/tokenizer/token.php',
        'mageekguy\\atoum\\reader' => __DIR__ . '/..' . '/atoum/atoum/classes/reader.php',
        'mageekguy\\atoum\\readers\\std\\in' => __DIR__ . '/..' . '/atoum/atoum/classes/readers/std/in.php',
        'mageekguy\\atoum\\report' => __DIR__ . '/..' . '/atoum/atoum/classes/report.php',
        'mageekguy\\atoum\\report\\field' => __DIR__ . '/..' . '/atoum/atoum/classes/report/field.php',
        'mageekguy\\atoum\\report\\field\\decorator' => __DIR__ . '/..' . '/atoum/atoum/classes/report/field/decorator.php',
        'mageekguy\\atoum\\report\\field\\decorators\\travis\\fold' => __DIR__ . '/..' . '/atoum/atoum/classes/report/field/decorators/travis/fold.php',
        'mageekguy\\atoum\\report\\fields\\event' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/event.php',
        'mageekguy\\atoum\\report\\fields\\runner' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner.php',
        'mageekguy\\atoum\\report\\fields\\runner\\atoum' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/atoum.php',
        'mageekguy\\atoum\\report\\fields\\runner\\atoum\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/atoum/cli.php',
        'mageekguy\\atoum\\report\\fields\\runner\\atoum\\logo' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/atoum/logo.php',
        'mageekguy\\atoum\\report\\fields\\runner\\atoum\\path' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/atoum/path.php',
        'mageekguy\\atoum\\report\\fields\\runner\\atoum\\path\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/atoum/path/cli.php',
        'mageekguy\\atoum\\report\\fields\\runner\\atoum\\phing' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/atoum/phing.php',
        'mageekguy\\atoum\\report\\fields\\runner\\atoum\\version' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/atoum/version.php',
        'mageekguy\\atoum\\report\\fields\\runner\\atoum\\version\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/atoum/version/cli.php',
        'mageekguy\\atoum\\report\\fields\\runner\\coverage' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/coverage.php',
        'mageekguy\\atoum\\report\\fields\\runner\\coverage\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/coverage/cli.php',
        'mageekguy\\atoum\\report\\fields\\runner\\coverage\\html' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/coverage/html.php',
        'mageekguy\\atoum\\report\\fields\\runner\\coverage\\treemap' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/coverage/treemap.php',
        'mageekguy\\atoum\\report\\fields\\runner\\duration' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/duration.php',
        'mageekguy\\atoum\\report\\fields\\runner\\duration\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/duration/cli.php',
        'mageekguy\\atoum\\report\\fields\\runner\\duration\\phing' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/duration/phing.php',
        'mageekguy\\atoum\\report\\fields\\runner\\errors' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/errors.php',
        'mageekguy\\atoum\\report\\fields\\runner\\errors\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/errors/cli.php',
        'mageekguy\\atoum\\report\\fields\\runner\\event' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/event.php',
        'mageekguy\\atoum\\report\\fields\\runner\\event\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/event/cli.php',
        'mageekguy\\atoum\\report\\fields\\runner\\event\\cli\\dot' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/event/cli/dot.php',
        'mageekguy\\atoum\\report\\fields\\runner\\exceptions' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/exceptions.php',
        'mageekguy\\atoum\\report\\fields\\runner\\exceptions\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/exceptions/cli.php',
        'mageekguy\\atoum\\report\\fields\\runner\\failures' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/failures.php',
        'mageekguy\\atoum\\report\\fields\\runner\\failures\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/failures/cli.php',
        'mageekguy\\atoum\\report\\fields\\runner\\failures\\execute' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/failures/execute.php',
        'mageekguy\\atoum\\report\\fields\\runner\\failures\\execute\\macos\\macvim' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/failures/execute/macos/macvim.php',
        'mageekguy\\atoum\\report\\fields\\runner\\failures\\execute\\macos\\phpstorm' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/failures/execute/macos/phpstorm.php',
        'mageekguy\\atoum\\report\\fields\\runner\\failures\\execute\\unix\\gedit' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/failures/execute/unix/gedit.php',
        'mageekguy\\atoum\\report\\fields\\runner\\failures\\execute\\unix\\gvim' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/failures/execute/unix/gvim.php',
        'mageekguy\\atoum\\report\\fields\\runner\\failures\\execute\\unix\\phpstorm' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/failures/execute/unix/phpstorm.php',
        'mageekguy\\atoum\\report\\fields\\runner\\outputs' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/outputs.php',
        'mageekguy\\atoum\\report\\fields\\runner\\outputs\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/outputs/cli.php',
        'mageekguy\\atoum\\report\\fields\\runner\\php\\path' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/php/path.php',
        'mageekguy\\atoum\\report\\fields\\runner\\php\\path\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/php/path/cli.php',
        'mageekguy\\atoum\\report\\fields\\runner\\php\\version' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/php/version.php',
        'mageekguy\\atoum\\report\\fields\\runner\\php\\version\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/php/version/cli.php',
        'mageekguy\\atoum\\report\\fields\\runner\\result' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/result.php',
        'mageekguy\\atoum\\report\\fields\\runner\\result\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/result/cli.php',
        'mageekguy\\atoum\\report\\fields\\runner\\result\\logo' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/result/logo.php',
        'mageekguy\\atoum\\report\\fields\\runner\\result\\notifier' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/result/notifier.php',
        'mageekguy\\atoum\\report\\fields\\runner\\result\\notifier\\image' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/result/notifier/image.php',
        'mageekguy\\atoum\\report\\fields\\runner\\result\\notifier\\image\\growl' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/result/notifier/image/growl.php',
        'mageekguy\\atoum\\report\\fields\\runner\\result\\notifier\\image\\libnotify' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/result/notifier/image/libnotify.php',
        'mageekguy\\atoum\\report\\fields\\runner\\result\\notifier\\terminal' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/result/notifier/terminal.php',
        'mageekguy\\atoum\\report\\fields\\runner\\tap\\plan' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/tap/plan.php',
        'mageekguy\\atoum\\report\\fields\\runner\\tests\\blank' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/tests/blank.php',
        'mageekguy\\atoum\\report\\fields\\runner\\tests\\blank\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/tests/blank/cli.php',
        'mageekguy\\atoum\\report\\fields\\runner\\tests\\coverage' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/tests/coverage.php',
        'mageekguy\\atoum\\report\\fields\\runner\\tests\\coverage\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/tests/coverage/cli.php',
        'mageekguy\\atoum\\report\\fields\\runner\\tests\\coverage\\phing' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/tests/coverage/phing.php',
        'mageekguy\\atoum\\report\\fields\\runner\\tests\\duration' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/tests/duration.php',
        'mageekguy\\atoum\\report\\fields\\runner\\tests\\duration\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/tests/duration/cli.php',
        'mageekguy\\atoum\\report\\fields\\runner\\tests\\memory' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/tests/memory.php',
        'mageekguy\\atoum\\report\\fields\\runner\\tests\\memory\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/tests/memory/cli.php',
        'mageekguy\\atoum\\report\\fields\\runner\\tests\\memory\\phing' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/tests/memory/phing.php',
        'mageekguy\\atoum\\report\\fields\\runner\\tests\\skipped' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/tests/skipped.php',
        'mageekguy\\atoum\\report\\fields\\runner\\tests\\skipped\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/tests/skipped/cli.php',
        'mageekguy\\atoum\\report\\fields\\runner\\tests\\uncompleted' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/tests/uncompleted.php',
        'mageekguy\\atoum\\report\\fields\\runner\\tests\\uncompleted\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/runner/tests/uncompleted/cli.php',
        'mageekguy\\atoum\\report\\fields\\test\\duration' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/test/duration.php',
        'mageekguy\\atoum\\report\\fields\\test\\duration\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/test/duration/cli.php',
        'mageekguy\\atoum\\report\\fields\\test\\duration\\phing' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/test/duration/phing.php',
        'mageekguy\\atoum\\report\\fields\\test\\event' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/test/event.php',
        'mageekguy\\atoum\\report\\fields\\test\\event\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/test/event/cli.php',
        'mageekguy\\atoum\\report\\fields\\test\\event\\phing' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/test/event/phing.php',
        'mageekguy\\atoum\\report\\fields\\test\\event\\tap' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/test/event/tap.php',
        'mageekguy\\atoum\\report\\fields\\test\\memory' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/test/memory.php',
        'mageekguy\\atoum\\report\\fields\\test\\memory\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/test/memory/cli.php',
        'mageekguy\\atoum\\report\\fields\\test\\memory\\phing' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/test/memory/phing.php',
        'mageekguy\\atoum\\report\\fields\\test\\run' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/test/run.php',
        'mageekguy\\atoum\\report\\fields\\test\\run\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/test/run/cli.php',
        'mageekguy\\atoum\\report\\fields\\test\\run\\phing' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/test/run/phing.php',
        'mageekguy\\atoum\\report\\fields\\test\\travis' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/test/travis.php',
        'mageekguy\\atoum\\report\\fields\\test\\travis\\start' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/test/travis/start.php',
        'mageekguy\\atoum\\report\\fields\\test\\travis\\stop' => __DIR__ . '/..' . '/atoum/atoum/classes/report/fields/test/travis/stop.php',
        'mageekguy\\atoum\\report\\writers\\asynchronous' => __DIR__ . '/..' . '/atoum/atoum/classes/report/writers/asynchronous.php',
        'mageekguy\\atoum\\report\\writers\\realtime' => __DIR__ . '/..' . '/atoum/atoum/classes/report/writers/realtime.php',
        'mageekguy\\atoum\\reports\\asynchronous' => __DIR__ . '/..' . '/atoum/atoum/classes/reports/asynchronous.php',
        'mageekguy\\atoum\\reports\\asynchronous\\builder' => __DIR__ . '/..' . '/atoum/atoum/classes/reports/asynchronous/builder.php',
        'mageekguy\\atoum\\reports\\asynchronous\\clover' => __DIR__ . '/..' . '/atoum/atoum/classes/reports/asynchronous/clover.php',
        'mageekguy\\atoum\\reports\\asynchronous\\coveralls' => __DIR__ . '/..' . '/atoum/atoum/classes/reports/asynchronous/coveralls.php',
        'mageekguy\\atoum\\reports\\asynchronous\\vim' => __DIR__ . '/..' . '/atoum/atoum/classes/reports/asynchronous/vim.php',
        'mageekguy\\atoum\\reports\\asynchronous\\xunit' => __DIR__ . '/..' . '/atoum/atoum/classes/reports/asynchronous/xunit.php',
        'mageekguy\\atoum\\reports\\realtime' => __DIR__ . '/..' . '/atoum/atoum/classes/reports/realtime.php',
        'mageekguy\\atoum\\reports\\realtime\\cli' => __DIR__ . '/..' . '/atoum/atoum/classes/reports/realtime/cli.php',
        'mageekguy\\atoum\\reports\\realtime\\cli\\dot' => __DIR__ . '/..' . '/atoum/atoum/classes/reports/realtime/cli/dot.php',
        'mageekguy\\atoum\\reports\\realtime\\cli\\light' => __DIR__ . '/..' . '/atoum/atoum/classes/reports/realtime/cli/light.php',
        'mageekguy\\atoum\\reports\\realtime\\cli\\travis' => __DIR__ . '/..' . '/atoum/atoum/classes/reports/realtime/cli/travis.php',
        'mageekguy\\atoum\\reports\\realtime\\phing' => __DIR__ . '/..' . '/atoum/atoum/classes/reports/realtime/phing.php',
        'mageekguy\\atoum\\reports\\realtime\\tap' => __DIR__ . '/..' . '/atoum/atoum/classes/reports/realtime/tap.php',
        'mageekguy\\atoum\\runner' => __DIR__ . '/..' . '/atoum/atoum/classes/runner.php',
        'mageekguy\\atoum\\runner\\score' => __DIR__ . '/..' . '/atoum/atoum/classes/runner/score.php',
        'mageekguy\\atoum\\score' => __DIR__ . '/..' . '/atoum/atoum/classes/score.php',
        'mageekguy\\atoum\\score\\coverage' => __DIR__ . '/..' . '/atoum/atoum/classes/score/coverage.php',
        'mageekguy\\atoum\\script' => __DIR__ . '/..' . '/atoum/atoum/classes/script.php',
        'mageekguy\\atoum\\script\\arguments\\parser' => __DIR__ . '/..' . '/atoum/atoum/classes/script/arguments/parser.php',
        'mageekguy\\atoum\\script\\configurable' => __DIR__ . '/..' . '/atoum/atoum/classes/script/configurable.php',
        'mageekguy\\atoum\\script\\prompt' => __DIR__ . '/..' . '/atoum/atoum/classes/script/prompt.php',
        'mageekguy\\atoum\\scripts\\builder' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/builder.php',
        'mageekguy\\atoum\\scripts\\builder\\vcs' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/builder/vcs.php',
        'mageekguy\\atoum\\scripts\\builder\\vcs\\svn' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/builder/vcs/svn.php',
        'mageekguy\\atoum\\scripts\\compiler' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/compiler.php',
        'mageekguy\\atoum\\scripts\\coverage' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/coverage.php',
        'mageekguy\\atoum\\scripts\\git\\pusher' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/git/pusher.php',
        'mageekguy\\atoum\\scripts\\phar\\generator' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/phar/generator.php',
        'mageekguy\\atoum\\scripts\\phar\\stub' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/phar/stub.php',
        'mageekguy\\atoum\\scripts\\runner' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/runner.php',
        'mageekguy\\atoum\\scripts\\runner\\looper' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/runner/looper.php',
        'mageekguy\\atoum\\scripts\\runner\\loopers\\prompt' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/runner/loopers/prompt.php',
        'mageekguy\\atoum\\scripts\\tagger' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/tagger.php',
        'mageekguy\\atoum\\scripts\\tagger\\engine' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/tagger/engine.php',
        'mageekguy\\atoum\\scripts\\treemap' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/treemap.php',
        'mageekguy\\atoum\\scripts\\treemap\\analyzer' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/treemap/analyzer.php',
        'mageekguy\\atoum\\scripts\\treemap\\analyzer\\generic' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/treemap/analyzer/generic.php',
        'mageekguy\\atoum\\scripts\\treemap\\analyzers\\size' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/treemap/analyzers/size.php',
        'mageekguy\\atoum\\scripts\\treemap\\analyzers\\sloc' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/treemap/analyzers/sloc.php',
        'mageekguy\\atoum\\scripts\\treemap\\analyzers\\token' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/treemap/analyzers/token.php',
        'mageekguy\\atoum\\scripts\\treemap\\categorizer' => __DIR__ . '/..' . '/atoum/atoum/classes/scripts/treemap/categorizer.php',
        'mageekguy\\atoum\\superglobals' => __DIR__ . '/..' . '/atoum/atoum/classes/superglobals.php',
        'mageekguy\\atoum\\template' => __DIR__ . '/..' . '/atoum/atoum/classes/template.php',
        'mageekguy\\atoum\\template\\data' => __DIR__ . '/..' . '/atoum/atoum/classes/template/data.php',
        'mageekguy\\atoum\\template\\iterator' => __DIR__ . '/..' . '/atoum/atoum/classes/template/iterator.php',
        'mageekguy\\atoum\\template\\parser' => __DIR__ . '/..' . '/atoum/atoum/classes/template/parser.php',
        'mageekguy\\atoum\\template\\parser\\exception' => __DIR__ . '/..' . '/atoum/atoum/classes/template/parser/exception.php',
        'mageekguy\\atoum\\template\\tag' => __DIR__ . '/..' . '/atoum/atoum/classes/template/tag.php',
        'mageekguy\\atoum\\test' => __DIR__ . '/..' . '/atoum/atoum/classes/test.php',
        'mageekguy\\atoum\\test\\adapter' => __DIR__ . '/..' . '/atoum/atoum/classes/test/adapter.php',
        'mageekguy\\atoum\\test\\adapter\\call' => __DIR__ . '/..' . '/atoum/atoum/classes/test/adapter/call.php',
        'mageekguy\\atoum\\test\\adapter\\call\\arguments\\decorator' => __DIR__ . '/..' . '/atoum/atoum/classes/test/adapter/call/arguments/decorator.php',
        'mageekguy\\atoum\\test\\adapter\\call\\decorator' => __DIR__ . '/..' . '/atoum/atoum/classes/test/adapter/call/decorator.php',
        'mageekguy\\atoum\\test\\adapter\\call\\decorators\\addClass' => __DIR__ . '/..' . '/atoum/atoum/classes/test/adapter/call/decorators/addClass.php',
        'mageekguy\\atoum\\test\\adapter\\calls' => __DIR__ . '/..' . '/atoum/atoum/classes/test/adapter/calls.php',
        'mageekguy\\atoum\\test\\adapter\\calls\\decorator' => __DIR__ . '/..' . '/atoum/atoum/classes/test/adapter/calls/decorator.php',
        'mageekguy\\atoum\\test\\adapter\\invoker' => __DIR__ . '/..' . '/atoum/atoum/classes/test/adapter/invoker.php',
        'mageekguy\\atoum\\test\\adapter\\storage' => __DIR__ . '/..' . '/atoum/atoum/classes/test/adapter/storage.php',
        'mageekguy\\atoum\\test\\asserter\\generator' => __DIR__ . '/..' . '/atoum/atoum/classes/test/asserter/generator.php',
        'mageekguy\\atoum\\test\\assertion\\aliaser' => __DIR__ . '/..' . '/atoum/atoum/classes/test/assertion/aliaser.php',
        'mageekguy\\atoum\\test\\assertion\\manager' => __DIR__ . '/..' . '/atoum/atoum/classes/test/assertion/manager.php',
        'mageekguy\\atoum\\test\\assertion\\manager\\exception' => __DIR__ . '/..' . '/atoum/atoum/classes/test/assertion/manager/exception.php',
        'mageekguy\\atoum\\test\\data\\provider' => __DIR__ . '/..' . '/atoum/atoum/classes/test/data/provider.php',
        'mageekguy\\atoum\\test\\data\\provider\\aggregator' => __DIR__ . '/..' . '/atoum/atoum/classes/test/data/provider/aggregator.php',
        'mageekguy\\atoum\\test\\data\\provider\\object\\exceptions\\mandatoryArgument' => __DIR__ . '/..' . '/atoum/atoum/classes/test/data/provider/object/exceptions/mandatoryArgument.php',
        'mageekguy\\atoum\\test\\data\\provider\\object\\exceptions\\privateConstructor' => __DIR__ . '/..' . '/atoum/atoum/classes/test/data/provider/object/exceptions/privateConstructor.php',
        'mageekguy\\atoum\\test\\data\\providers\\mock' => __DIR__ . '/..' . '/atoum/atoum/classes/test/data/providers/mock.php',
        'mageekguy\\atoum\\test\\data\\providers\\phpObject' => __DIR__ . '/..' . '/atoum/atoum/classes/test/data/providers/phpObject.php',
        'mageekguy\\atoum\\test\\data\\set' => __DIR__ . '/..' . '/atoum/atoum/classes/test/data/set.php',
        'mageekguy\\atoum\\test\\engine' => __DIR__ . '/..' . '/atoum/atoum/classes/test/engine.php',
        'mageekguy\\atoum\\test\\engines\\concurrent' => __DIR__ . '/..' . '/atoum/atoum/classes/test/engines/concurrent.php',
        'mageekguy\\atoum\\test\\engines\\inline' => __DIR__ . '/..' . '/atoum/atoum/classes/test/engines/inline.php',
        'mageekguy\\atoum\\test\\engines\\isolate' => __DIR__ . '/..' . '/atoum/atoum/classes/test/engines/isolate.php',
        'mageekguy\\atoum\\test\\exceptions\\runtime' => __DIR__ . '/..' . '/atoum/atoum/classes/test/exceptions/runtime.php',
        'mageekguy\\atoum\\test\\exceptions\\skip' => __DIR__ . '/..' . '/atoum/atoum/classes/test/exceptions/skip.php',
        'mageekguy\\atoum\\test\\exceptions\\stop' => __DIR__ . '/..' . '/atoum/atoum/classes/test/exceptions/stop.php',
        'mageekguy\\atoum\\test\\generator' => __DIR__ . '/..' . '/atoum/atoum/classes/test/generator.php',
        'mageekguy\\atoum\\test\\generator\\exception' => __DIR__ . '/..' . '/atoum/atoum/classes/test/generator/exception.php',
        'mageekguy\\atoum\\test\\mock\\generator' => __DIR__ . '/..' . '/atoum/atoum/classes/test/mock/generator.php',
        'mageekguy\\atoum\\test\\score' => __DIR__ . '/..' . '/atoum/atoum/classes/test/score.php',
        'mageekguy\\atoum\\tools\\diff' => __DIR__ . '/..' . '/atoum/atoum/classes/tools/diff.php',
        'mageekguy\\atoum\\tools\\diff\\decorator' => __DIR__ . '/..' . '/atoum/atoum/classes/tools/diff/decorator.php',
        'mageekguy\\atoum\\tools\\diffs\\variable' => __DIR__ . '/..' . '/atoum/atoum/classes/tools/diffs/variable.php',
        'mageekguy\\atoum\\tools\\variable\\analyzer' => __DIR__ . '/..' . '/atoum/atoum/classes/tools/variable/analyzer.php',
        'mageekguy\\atoum\\writer' => __DIR__ . '/..' . '/atoum/atoum/classes/writer.php',
        'mageekguy\\atoum\\writer\\decorator' => __DIR__ . '/..' . '/atoum/atoum/classes/writer/decorator.php',
        'mageekguy\\atoum\\writer\\decorators\\eol' => __DIR__ . '/..' . '/atoum/atoum/classes/writer/decorators/eol.php',
        'mageekguy\\atoum\\writer\\decorators\\prompt' => __DIR__ . '/..' . '/atoum/atoum/classes/writer/decorators/prompt.php',
        'mageekguy\\atoum\\writer\\decorators\\rtrim' => __DIR__ . '/..' . '/atoum/atoum/classes/writer/decorators/rtrim.php',
        'mageekguy\\atoum\\writer\\decorators\\trim' => __DIR__ . '/..' . '/atoum/atoum/classes/writer/decorators/trim.php',
        'mageekguy\\atoum\\writers\\file' => __DIR__ . '/..' . '/atoum/atoum/classes/writers/file.php',
        'mageekguy\\atoum\\writers\\http' => __DIR__ . '/..' . '/atoum/atoum/classes/writers/http.php',
        'mageekguy\\atoum\\writers\\http\\exception' => __DIR__ . '/..' . '/atoum/atoum/classes/writers/http/exception.php',
        'mageekguy\\atoum\\writers\\mail' => __DIR__ . '/..' . '/atoum/atoum/classes/writers/mail.php',
        'mageekguy\\atoum\\writers\\std' => __DIR__ . '/..' . '/atoum/atoum/classes/writers/std.php',
        'mageekguy\\atoum\\writers\\std\\err' => __DIR__ . '/..' . '/atoum/atoum/classes/writers/std/err.php',
        'mageekguy\\atoum\\writers\\std\\out' => __DIR__ . '/..' . '/atoum/atoum/classes/writers/std/out.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit065ced53282fa1d1adde9432547fbbc5::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit065ced53282fa1d1adde9432547fbbc5::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit065ced53282fa1d1adde9432547fbbc5::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit065ced53282fa1d1adde9432547fbbc5::$classMap;

        }, null, ClassLoader::class);
    }
}
